In [ ]:
#task1---preprocessing
import numpy as np
import pandas as pd

task-1  ------> data preprocessing

In [9]:
#reading data
dfrm = pd.read_csv('drugsAssgn2.csv')
print(dfrm.head(),'\n')


   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY 



In [71]:
#feature extraction
x = dfrm.iloc[:,0:5]
print(x.head(),'\n')
y = dfrm.iloc[:,5]
print(x.head(),'\n')


   Age Sex      BP Cholesterol  Na_to_K
0   23   F    HIGH        HIGH   25.355
1   47   M     LOW        HIGH   13.093
2   47   M     LOW        HIGH   10.114
3   28   F  NORMAL        HIGH    7.798
4   61   F     LOW        HIGH   18.043 

   Age Sex      BP Cholesterol  Na_to_K
0   23   F    HIGH        HIGH   25.355
1   47   M     LOW        HIGH   13.093
2   47   M     LOW        HIGH   10.114
3   28   F  NORMAL        HIGH    7.798
4   61   F     LOW        HIGH   18.043 



In [76]:
#traintest split
from sklearn.model_selection import train_test_split
xtr,xte,ytr,yte = train_test_split(x,y,test_size=0.2,random_state=10)
#encoding
xtr = pd.get_dummies(xtr, columns=['Sex','BP','Cholesterol'])
xte = pd.get_dummies(xte, columns=['Sex','BP','Cholesterol'])

num_classes = len(np.unique(y))
ytr = pd.get_dummies(ytr).values
yte = pd.get_dummies(yte).values

print('after encoding input values are','\n')
xtr.head()

after encoding input values are 



Age  Na_to_K  Sex_F  Sex_M  BP_HIGH  BP_LOW  BP_NORMAL  Cholesterol_HIGH  \
190   58   18.991      0      1        1       0          0                 1   
7     41   11.037      0      1        0       1          0                 1   
26    31   30.366      0      1        1       0          0                 1   
138   51   11.343      0      1        1       0          0                 0   
58    60   10.091      0      1        0       0          1                 0   

     Cholesterol_NORMAL  
190                   0  
7                     0  
26                    0  
138                   1  
58                    1

In [78]:
print('target variable encoding : ','\n')
print(ytr[0:20])

target variable encoding :  

[[1 0 0 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]]


TASK-2------MODEL FIT

In [79]:
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(10, activation='relu', input_dim=xtr.shape[1]))
model.add(Dense(10, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))


In [80]:
# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(xtr, ytr, epochs=1000, batch_size=32, verbose=1)

Epoch 1/1000
5/5 [==============================] - 1s 2ms/step - loss: 5.6005 - accuracy: 0.1063
Epoch 2/1000
5/5 [==============================] - 0s 2ms/step - loss: 4.6377 - accuracy: 0.1063
Epoch 3/1000
5/5 [==============================] - 0s 2ms/step - loss: 3.8344 - accuracy: 0.1063
Epoch 4/1000
5/5 [==============================] - 0s 3ms/step - loss: 3.1884 - accuracy: 0.1063
Epoch 5/1000
5/5 [==============================] - 0s 3ms/step - loss: 2.6845 - accuracy: 0.1063
Epoch 6/1000
5/5 [==============================] - 0s 2ms/step - loss: 2.3183 - accuracy: 0.1125
Epoch 7/1000
5/5 [==============================] - 0s 1ms/step - loss: 2.0217 - accuracy: 0.3187
Epoch 8/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.7877 - accuracy: 0.3688
Epoch 9/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.6255 - accuracy: 0.4187
Epoch 10/1000
5/5 [==============================] - 0s 3ms/step - loss: 1.4917 - accuracy: 0.4437
Epoch 11/1000
5/5 [

TASK-3  -----  EVALUATION

In [81]:
# Evaluate the model on the test data
loss, accuracy = model.evaluate(xte, yte, verbose=0)
print('Test Loss:', loss)
print('Test Accuracy:', accuracy)

Test Loss: 0.23064768314361572
Test Accuracy: 0.949999988079071


In [82]:
dfrand = pd.DataFrame({'age':[23],'Sex':['F'],'BP':['HIGH'],'Cholesterol':['HIGH'],'Na_to_K':[25.355]})
#we can change values in the above to obtain required random input
dfrandE = pd.get_dummies(dfrand, columns=['Sex','BP','Cholesterol'])
dfrandE = dfrandE.reindex(columns=xtr.columns, fill_value=0)
xPred = model.predict(dfrandE)
labels=['DrugY','drugA','drugB','drugC','drugX']
y_decoded = [labels[np.argmax(row)] for row in xPred]
print('predicted drug:',y_decoded,'----->','which is correct according to the given raw data')



1/1 [==============================] - 0s 55ms/step
predicted drug: ['DrugY'] -----> which is correct according to the given raw data
